todoWeb/Pages/Tasks/TaskDays/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using todoWeb.Data.Stores;
using todoWeb.Data;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace todoWeb.Pages.Tasks.TaskDays
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ITaskStore _taskStore;

        public CreateModel(ITaskStore taskStore)
        {
            _taskStore = taskStore;
        }

        [Required]
        [BindProperty]
        [DataType(DataType.Date)]
        public DateTime InputDate { get; set; }

        public void OnGet()
        {
            InputDate = DateTime.Now;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // TODO: Check, if this day already exists and return with a warning? Not needed ATM.
            await _taskStore.GetTaskDayAsync(DateOnly.FromDateTime(InputDate));
            await _taskStore.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

todoWeb/Pages/Tasks/TaskDays/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using todoWeb.Data;
using todoWeb.Data.Stores;

namespace todoWeb.Pages.Tasks.TaskDays
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ITaskStore _taskStore;

        public IndexModel(ITaskStore taskStore)
        {
            _taskStore = taskStore;
        }

        public IList<TaskDay>? TaskDays { get; set; }

        public async void OnGet()
        {
            TaskDays = await _taskStore.GetTaskDaysAsync();
        }

        public async Task<IActionResult> OnPostDeleteTaskAsync(int id)
        {
            var task = await _taskStore.GetTaskAsync(id);
            if (task != null)
            {
                await _taskStore.RemoveTaskAsync(task);
                await _taskStore.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostToggleTaskAsync(int id)
        {
            var task = await _taskStore.GetTaskAsync(id);
            if (task != null)
            {
                task.IsCompleted = !task.IsCompleted;
                await _taskStore.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(string id)
        {
            // TODO: Well, if we want to use DateOnly instead of string, we need to add a custom type converter/model binder.
            var dateOnlyId = DateOnly.Parse(id);
            var taskDay = await _taskStore.GetTaskDayAsync(dateOnlyId, false);

            if (taskDay != null)
            {
                await _taskStore.RemoveTaskDayAsync(taskDay);
                await _taskStore.SaveChangesAsync();
            }

            return RedirectToPage();
        }
    }
}

todoWeb/Pages/Tasks/TaskItems/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using todoWeb.Data.Stores;
using todoWeb.Data;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace todoWeb.Pages.Tasks.TaskItems
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ITaskStore _taskStore;

        public CreateModel(ITaskStore taskStore)
        {
            _taskStore = taskStore;
        }

        [Required]
        [BindProperty]
        public string? TaskDescription { get; set; }

        [BindProperty]
        [HiddenInput]
        public string? TaskDayId { get; set; }

        public void OnGet(string id)
        {
            TaskDayId = id;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || string.IsNullOrEmpty(TaskDayId))
            {
                return Page();
            }

            var taskDay = (await _taskStore.GetTaskDayAsync(DateOnly.Parse(TaskDayId)))!;

            taskDay.Tasks.Add(new TaskItem() { Description = TaskDescription });
            await _taskStore.SaveChangesAsync();

            return RedirectToPage("../TaskDays/Index");
        }
    }
}

todoWeb/Pages/Tasks/TaskItems/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using todoWeb.Data.Stores;
using todoWeb.Data;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace todoWeb.Pages.Tasks.TaskItems
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly ITaskStore _taskStore;

        public EditModel(ITaskStore taskStore)
        {
            _taskStore = taskStore;
        }

        [Required]
        [BindProperty]
        public string? TaskDescription { get; set; }

        [BindProperty]
        [HiddenInput]
        public int TaskId { get; set; }

        public async Task<IActionResult> OnGet(int id)
        {
            TaskId = id;
            var task = await _taskStore.GetTaskAsync(TaskId);
            if (task == null)
            {
                return RedirectToPage("../TaskDays/Index");
            }

            TaskDescription = task.Description;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var task = await _taskStore.GetTaskAsync(TaskId);
            if (task != null)
            {
                task.Description = TaskDescription;
                await _taskStore.UpdateTaskAsync(task);
                await _taskStore.SaveChangesAsync();
            }

            return RedirectToPage("../TaskDays/Index");
        }
    }
}

todoWeb/Pages/Tasks/TaskDays/Create.cshtml
@page
@model todoWeb.Pages.Tasks.TaskDays.CreateModel
@{
    ViewData["Title"] = "Add task day";
}

<div class="row">
    <div class="col-md-4">
        <form id="createTaskDay" method="post">
            <h2>@ViewData["Title"]</h2>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            <div class="form-floating mb-3" lang="pl">
                <input asp-for="InputDate" class="form-control"/>
                <label asp-for="InputDate">Date</label>
                <span asp-validation-for="InputDate" class="text-danger"></span>
            </div>
            <button id="createSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add</button>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

todoWeb/Pages/Tasks/TaskDays/Index.cshtml
@page
@model todoWeb.Pages.Tasks.TaskDays.IndexModel
@{
    ViewData["Title"] = "Task overview";
}

<h1>Tasks</h1>
<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Tasks</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.TaskDays != null)
            {
                foreach (var taskDay in Model.TaskDays)
                {
                    <tr>
                        <td>@taskDay.TaskDate</td>
                        <td>
                            <table class="table">
                                <tbody>
                                    @foreach(var task in taskDay.Tasks)
                                    {
                                        <tr>
                                            <td style="@(@task.IsCompleted ? "text-decoration: line-through;" : string.Empty)"> @task.Description</td>
                                            <td>
                                                <a asp-page="../TaskItems/Edit" asp-route-id="@task.Id"><input type="button" class="btn btn-primary" value="edit" /></a>
                                                <button type="submit" class="btn btn-primary" asp-page-handler="toggleTask" asp-route-id="@task.Id">toggle</button>
                                                <button type="submit" class="btn btn-primary" asp-page-handler="deleteTask" asp-route-id="@task.Id">delete task</button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                        <td>
                            <a asp-page="../TaskItems/Create" asp-route-id="@taskDay.TaskDate"><input type="button" class="btn btn-primary"  value="add task" /></a>
                            <button type="submit" class="btn btn-primary" asp-page-handler="delete" asp-route-id="@taskDay.TaskDate">delete day</button>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a asp-page="Create">Add new day</a>
</form>